org: vlindhol
app: multi-demo-app
service: multi-demo-app

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: production

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  textQuery:
    handler: app/handler.textQuery
    # In a real production app, no secrets should obviously be in git!
    # The most robust system would be to use AWS Parameter Store, but the
    # Serverless Pro Dashboard could also be used.
    environment:
      OPEN_WEATHER_TOKEN: f8ef2e048850097157e3272f98fb8d94
    events:
      - http:
          path: text-query
          method: post
